### ISSUE TITLE
Old gmpy dependency

### ISSUE THREAD

**Issue by NicoHood** [bwesterb/py-seccure#11]
gmpy2 is out, would it be possible for you to update to this release? That'd be simpler to maintain as distribution packager. Thanks.

Checkout the different branches:
https://github.com/aleaxit/gmpy

**Comment by bwesterb** [comment]
Thanks for reporting.  I'll try to port to gmpy2.  (Same with github.com/bwesterb/pol )

**Comment by bwesterb** [comment]
Debian stable doesn't seem to come with a sufficiently recent version of MPC – so I can't use gmpy2 yet.  See https://travis-ci.org/bwesterb/py-seccure/jobs/167932206

**Comment by NicoHood** [comment]
Could you make both compatible? Because on the other side on archlinux it is a struggle to package such old versions, even if newer are already available. Then you can slowly drop the support for the old version.

I am really not aware how much incompatible the new version is, but if its totally incompatible you might make a cut here and start only with new depenedencies in the next version. Also can't you use pip anyways for debian old software?

**Comment by bwesterb** [comment]
I can certainly try to make it compatible with both.

> Also can't you use pip anyways for debian old software?

Please take a look at the link I posted: it tries to install gmpy2 via pip, but it fails as the libmpc-dev package on Debian is too old.

**Comment by CromefireHD** [comment]
This issue causes still a lot of issues, for example with readthedocs please try to fix this again, some time went through since then

**Comment by bwesterb** [comment]
@CromefireHD In what way does it cause issues with readthedocs?  I can't fix it until Debian packages a more recent version of MPC.

**Comment by CromefireHD** [comment]
The problem is, that there are headers not found and is there really still no update?

**Comment by bwesterb** [comment]
Sorry, I still don't understand how readthedocs is related.  Does it depend on `py-seccure`?

> and is there really still no update?

After your previous comment I restarted the travis job to check whether it works now, but the MPC version in Debian stable still seems to be too old, see https://travis-ci.org/bwesterb/py-seccure/jobs/167932206

**Comment by CromefireHD** [comment]
My project does depend on py-seccure and it should build docs at readthedocs

**Comment by bwesterb** [comment]
So what problem do you hit with the current version of py-seccure.  It should just work fine. This issue was raised by a maintainer which likes to drop support for gmpy in favour of gmpy2.

**Comment by CromefireHD** [comment]
The problem is, I specify seccure in requirements.txt and build fails

**Comment by bwesterb** [comment]
Ah, that explains! You are not talking about this issue, but about a different issue.  Could you please create a separate issue and include the output of the failing build?

**Comment by bwesterb** [comment]
With the release of Debian Buster, the MPC version has been updated.  `py-seccure` now uses `gmpy2` instead of `gmpy`.
