### ISSUE TITLE
py-seccure requirement fails on readthedocs (because old gmpy?)

### ISSUE THREAD

**Issue by CromefireHD** [bwesterb/py-seccure#12]
[doc_fail.txt](https://github.com/bwesterb/py-seccure/files/888495/doc_fail.txt)

**Comment by bwesterb** [comment]
Have you installed the development package for libgmp?  On Debian you can do this with `apt-get install libgmp-dev`, like I mentioned in `README.md`.

**Comment by CromefireHD** [comment]
can't do this becaus it's on readthedocs, i can't change this

**Comment by bwesterb** [comment]
This is then clearly not an issue with `py-seccure`. Have you tried Googling for a solution?  I did, [this might solve it for you](http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules).

**Comment by CromefireHD** [comment]
What should I mock for gmpy simply "gmp" (I don't even know what gmp(y) is so. I didn't know, that it depends on c libraries, sorry)
