### ISSUE TITLE
Add support for ECDH

### ISSUE THREAD

**Issue by cromefire** [bwesterb/py-seccure#13]
Please add support for the Diffie–Hellman key exchange, because it's a often used Method to implement good and fast encryption

**Comment by bwesterb** [comment]
Implementing `seccure-dh` is listed under the *Please contribute!* section of the README. What is your use case?  If it's online – i.e. an attacker can time the operations – then you don't want to use `py-seccure` as it doesn't use constant-time crypto.  See the *timing attack* warning at the top of the README.

**Comment by CromefireHD** [comment]
It is in use for encrypting traffic that runs over a socket and as I doesn't know much about encryption so I'm sorry but I can't contribute
