### ISSUE TITLE
Smallest elliptic curve

### ISSUE THREAD

**Issue by aminhafsa** [bwesterb/py-seccure#14]
Hi, the smallest elliptic curve is secp112r1, is there a way i can make it even shorter?

**Comment by bwesterb** [comment]
You can add an even smaller curve by hand.  I wouldn't do that though: `secp112r1` is already quite weak, see for instance *How to choose the curve* in the [original seccure manual](http://point-at-infinity.org/seccure/seccure.1.html):

> Warning: the curves p112 and p128 do not satisfy demands for long-time security.
