### ISSUE TITLE
Problems with different curves

### ISSUE THREAD

**Issue by Dschorim** [bwesterb/py-seccure#19]
when I try to use a different curve than secp160r1 (the standard one), I sometimes get a ValueError when trying to encrypt a message, if this doesn't happen, I get an IntegrityError when trying to decrypt the message again

**Comment by bwesterb** [comment]
Thanks for reporting this.  The package already includes tests to work with different curves, so there is something odd here.  Could you please provide example code so I can reproduce the issue?

**Comment by Dschorim** [comment]
an example would be

import seccure
curve_to_use = "secp521r1/nistp521"
(private_key, public_key) = seccure.generate_keypair(curve=curve_to_use)
message = b"hello"
ciphertext = seccure.encrypt(message, public_key, curve=curve_to_use)
print(ciphertext)
decrypted = seccure.decrypt(ciphertext, private_key, curve=curve_to_use)
print(decrypted)

Executing this code multiple times produces either a ValueError or an IntegrityError

**Comment by bwesterb** [comment]
Ah, yes, that reproduces the issue.  It seems to be a problem with `generate_keypair`, which was added later on.  Writing a fix now.

**Comment by bwesterb** [comment]
Waiting for CI to finish checks.  Then I'll create a release.

**Comment by bwesterb** [comment]
Fix is in `0.4.1`.  Thanks for reporting and sorry for the issue!
