### ISSUE TITLE
Signature size + private key   

### ISSUE THREAD

**Issue by drorbar** [bwesterb/py-seccure#8]
Hi 

First of all - this module helped me a lot.
I encountered two problems while using it:
1. Why is there no way to create a random private key? like pycrypto provides? all the keys need a start string.
2. I often get different size for the signature (79 or 78), i guess the issue is the serialization, but this pop two questions:
    a. As far as I know, signature length should be fixed, am I mistaken?
    b. why there is no way to put max_length in the main sign module 

Thanks a lot

**Comment by bwesterb** [comment]
Nice to hear my work is helpful!

1. There is no simple cross-platform cryptography-strong random number source.  I could add a function that uses `pycrypto`'s implementation, but that would add a dependancy.  I'll add generating a random key using `pycrypto` as an example.
2. a. The signature is "just" a number (below a certain value).  Most random numbers below 1500 are 4 digits, but it might happen that you choose one of 3 digits (or even shorter).  This is no different.
2. b. I don't understand: what should the `max_length` argument do?

**Comment by bwesterb** [comment]
Oh, wait, silly me --- I already have a dependancy on `pycrypto`.  I  will add a function to create a random new key.

**Comment by JackSparrow94** [comment]
When you create signature you use serialize data function, and it can have a max_length value (the outlen arg).
But there is no way to give this function that argument

**Comment by bwesterb** [comment]
What is your use case?
